import {
  HealthcareFacility,
  LiveQueueItem,
  AppointmentRecord,
  ReferralRecord,
  DiagnosticTestItem,
  MedicineStockItem,
  HighRiskFollowup,
  DoctorProgressReportData,
} from '../src/types';

export const DEMO_FACILITIES: HealthcareFacility[] = [
  {
    id: 'FAC-SC-VELU',
    name: 'Arogya Vardhini Sub-Centre Velu',
    type: 'SUB_CENTRE',
    district: 'Pune',
    taluka: 'Bhor',
    village: 'Velu',
    contactNumber: '+91 94230 11001',
    address: 'Near Gram Panchayat, Velu Gaon, Taluka Bhor, Pune 412205',
    totalBeds: 2,
    availableBeds: 2,
    doctorCount: 1,
    hasTeleconsultation: true,
    hasEmergency108: true,
    operatingHours: '9:00 AM - 4:00 PM (Emergency 24/7 on call)',
    parentFacilityId: 'FAC-PHC-BHOR',
    coordinates: { lat: 18.2912, lng: 73.9015 },
  },
  {
    id: 'FAC-PHC-BHOR',
    name: 'Bhor Primary Health Centre (PHC)',
    type: 'PHC',
    district: 'Pune',
    taluka: 'Bhor',
    village: 'Bhor Town',
    contactNumber: '+91 02113 222100',
    address: 'Station Road, Bhor Town, District Pune, Maharashtra 412206',
    totalBeds: 10,
    availableBeds: 6,
    doctorCount: 3,
    hasTeleconsultation: true,
    hasEmergency108: true,
    operatingHours: '24 Hours (OPD: 8:00 AM - 2:00 PM & 4:00 PM - 6:00 PM)',
    parentFacilityId: 'FAC-RH-BHOR',
    coordinates: { lat: 18.1568, lng: 73.8447 },
  },
  {
    id: 'FAC-PHC-NASRAPUR',
    name: 'Nasrapur Primary Health Centre (PHC)',
    type: 'PHC',
    district: 'Pune',
    taluka: 'Bhor',
    village: 'Nasrapur',
    contactNumber: '+91 02113 242055',
    address: 'Pune-Bangalore Highway Junction, Nasrapur, Maharashtra 412213',
    totalBeds: 8,
    availableBeds: 4,
    doctorCount: 2,
    hasTeleconsultation: true,
    hasEmergency108: true,
    operatingHours: '24 Hours (OPD: 8:30 AM - 1:30 PM)',
    parentFacilityId: 'FAC-RH-BHOR',
    coordinates: { lat: 18.2541, lng: 73.8962 },
  },
  {
    id: 'FAC-RH-BHOR',
    name: 'Bhor Rural Hospital (Sub-District Hospital)',
    type: 'RURAL_HOSPITAL',
    district: 'Pune',
    taluka: 'Bhor',
    village: 'Bhor',
    contactNumber: '+91 02113 222340',
    address: 'Shivaji Chowk, Bhor, District Pune, Maharashtra 412206',
    totalBeds: 30,
    availableBeds: 12,
    doctorCount: 8,
    hasTeleconsultation: true,
    hasEmergency108: true,
    operatingHours: '24 Hours Emergency & IPD, OPD: 8:00 AM - 2:00 PM',
    parentFacilityId: 'FAC-DH-AUNDH',
    coordinates: { lat: 18.159, lng: 73.8421 },
  },
  {
    id: 'FAC-DH-AUNDH',
    name: 'District Hospital Aundh, Pune',
    type: 'DISTRICT_HOSPITAL',
    district: 'Pune',
    taluka: 'Haveli',
    address: 'Near Chest Hospital, Aundh, Pune, Maharashtra 411027',
    contactNumber: '+91 020 2728 0100',
    totalBeds: 300,
    availableBeds: 68,
    doctorCount: 45,
    hasTeleconsultation: true,
    hasEmergency108: true,
    operatingHours: '24 Hours Emergency & Trauma, Specialist OPDs 9 AM - 1 PM',
    parentFacilityId: 'FAC-SGH-PUNE',
    coordinates: { lat: 18.5582, lng: 73.8077 },
  },
  {
    id: 'FAC-SGH-PUNE',
    name: 'Sassoon General Hospital & B.J. Medical College',
    type: 'SPECIALIST_CENTER',
    district: 'Pune',
    taluka: 'Pune City',
    address: 'Near Pune Railway Station, Sassoon Road, Pune 411001',
    contactNumber: '+91 020 2612 8000',
    totalBeds: 1200,
    availableBeds: 195,
    doctorCount: 220,
    hasTeleconsultation: true,
    hasEmergency108: true,
    operatingHours: '24x7 Multi-Specialty & Tertiary Referral Centre',
    coordinates: { lat: 18.5284, lng: 73.8742 },
  },
];

export const DEMO_LIVE_QUEUE: LiveQueueItem[] = [
  {
    id: 'Q-101',
    token: 'A-041',
    patientId: 'DEMO-001',
    patientName: 'Rahul Kumar Patil',
    patientAge: 38,
    patientGender: 'Male',
    patientPhone: '+91 98765 43210',
    triageCategory: 'CRITICAL',
    urgency: 'URGENT',
    status: 'SERVING',
    position: 0,
    estimatedWaitMinutes: 0,
    joinedAt: new Date(Date.now() - 35 * 60000).toISOString(),
    calledAt: new Date(Date.now() - 5 * 60000).toISOString(),
    chiefComplaint: 'Acute retrosternal chest pain radiating to left shoulder with cold sweats (2 hrs)',
    vitals: { bp: '168/104', spo2: 94, pulse: 108, temp: 37.1 },
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    assignedDoctorName: 'Dr. Ananya Deshmukh (Medical Officer)',
  },
  {
    id: 'Q-102',
    token: 'A-042',
    patientId: 'PAT002',
    patientName: 'Sunita Tai More',
    patientAge: 26,
    patientGender: 'Female',
    patientPhone: '+91 98220 54321',
    triageCategory: 'CRITICAL',
    urgency: 'URGENT',
    status: 'WAITING',
    position: 1,
    estimatedWaitMinutes: 8,
    joinedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    chiefComplaint: 'Pregnant 34 weeks, severe headache, pedal edema, elevated blood pressure',
    vitals: { bp: '162/106', spo2: 98, pulse: 92, temp: 36.8 },
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    assignedDoctorName: 'Dr. Ananya Deshmukh (Medical Officer)',
  },
  {
    id: 'Q-103',
    token: 'A-043',
    patientId: 'PAT004',
    patientName: 'Tukaram Shinde',
    patientAge: 62,
    patientGender: 'Male',
    patientPhone: '+91 94225 67890',
    triageCategory: 'MEDIUM',
    urgency: 'PRIORITY',
    status: 'WAITING',
    position: 2,
    estimatedWaitMinutes: 18,
    joinedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    chiefComplaint: 'Persistent productive cough with evening fever for 3 weeks, mild hemoptysis',
    vitals: { bp: '138/88', spo2: 95, pulse: 86, temp: 38.3 },
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    assignedDoctorName: 'Dr. Ananya Deshmukh (Medical Officer)',
  },
  {
    id: 'Q-104',
    token: 'A-044',
    patientId: 'PAT005',
    patientName: 'Baby Aarav Khare (Parent: Meena)',
    patientAge: 1.5,
    patientGender: 'Male',
    patientPhone: '+91 97664 12345',
    triageCategory: 'MEDIUM',
    urgency: 'PRIORITY',
    status: 'WAITING',
    position: 3,
    estimatedWaitMinutes: 28,
    joinedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    chiefComplaint: 'High fever 102°F with vomiting, refusal to feed, lethargy for 24 hours',
    vitals: { bp: '90/60', spo2: 96, pulse: 128, temp: 39.0 },
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    assignedDoctorName: 'Dr. Ananya Deshmukh (Medical Officer)',
  },
  {
    id: 'Q-105',
    token: 'A-045',
    patientId: 'DEMO-003',
    patientName: 'Ramesh Patil',
    patientAge: 54,
    patientGender: 'Male',
    patientPhone: '+91 97222 33445',
    triageCategory: 'STABLE',
    urgency: 'ROUTINE',
    status: 'WAITING',
    position: 4,
    estimatedWaitMinutes: 40,
    joinedAt: new Date(Date.now() - 50 * 60000).toISOString(),
    chiefComplaint: 'Routine follow-up for Type-2 Diabetes & Hypertension, monthly medication refill',
    vitals: { bp: '142/90', spo2: 98, pulse: 76, temp: 36.6 },
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    assignedDoctorName: 'Dr. Ananya Deshmukh (Medical Officer)',
  },
  {
    id: 'Q-106',
    token: 'A-046',
    patientId: 'DEMO-004',
    patientName: 'Savitri Devi Jagtap',
    patientAge: 46,
    patientGender: 'Female',
    patientPhone: '+91 96333 44556',
    triageCategory: 'STABLE',
    urgency: 'ROUTINE',
    status: 'WAITING',
    position: 5,
    estimatedWaitMinutes: 52,
    joinedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    chiefComplaint: 'Bilateral knee pain for 6 months, worse on walking up hill slopes',
    vitals: { bp: '126/82', spo2: 99, pulse: 72, temp: 36.7 },
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    assignedDoctorName: 'Dr. Ananya Deshmukh (Medical Officer)',
  },
];

export const DEMO_APPOINTMENTS: AppointmentRecord[] = [
  {
    id: 'APT-MH-201',
    token: 'A-042',
    patientId: 'PAT002',
    patientName: 'Sunita Tai More',
    patientPhone: '+91 98220 54321',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    department: 'Maternal & Child Health / High-Risk ANC',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Ananya Deshmukh',
    scheduledAt: new Date(Date.now() + 50 * 60000).toISOString(),
    appointmentTime: '11:30 AM',
    status: 'SCHEDULED',
    triageCategory: 'CRITICAL',
    isTeleconsult: false,
    oneHourReminderSent: true,
    notes: 'Pre-eclampsia screening alert triggered. Escorted by ASHA Vandana Tai.',
  },
  {
    id: 'APT-MH-202',
    token: 'A-047',
    patientId: 'PAT007',
    patientName: 'Anand Vitthal Rao',
    patientPhone: '+91 99231 99887',
    facilityId: 'FAC-RH-BHOR',
    facilityName: 'Bhor Rural Hospital',
    department: 'General Medicine & Diabetology',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Rahul Verma',
    scheduledAt: new Date(Date.now() + 110 * 60000).toISOString(),
    appointmentTime: '12:30 PM',
    status: 'SCHEDULED',
    triageCategory: 'MEDIUM',
    isTeleconsult: false,
    oneHourReminderSent: false,
    notes: 'Diabetic retinopathy screening follow-up.',
  },
  {
    id: 'APT-MH-203',
    token: 'T-012',
    patientId: 'DEMO-001',
    patientName: 'Rahul Kumar Patil',
    patientPhone: '+91 98765 43210',
    facilityId: 'FAC-DH-AUNDH',
    facilityName: 'District Hospital Aundh, Pune',
    department: 'Cardiology Tele-Specialist Clinic',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Rahul Verma (Cardiologist)',
    scheduledAt: new Date(Date.now() + 30 * 60000).toISOString(),
    appointmentTime: '11:15 AM',
    status: 'SCHEDULED',
    triageCategory: 'CRITICAL',
    isTeleconsult: true,
    oneHourReminderSent: true,
    notes: 'Assisted teleconsultation connecting Bhor PHC to District Cardiologist.',
  },
];

export const DEMO_REFERRALS: ReferralRecord[] = [
  {
    id: 'REF-MH-101',
    patientId: 'PAT002',
    patientName: 'Sunita Tai More',
    patientAge: 26,
    patientGender: 'Female',
    patientPhone: '+91 98220 54321',
    abhaId: 'sunita.more@abdm',
    referringFacilityId: 'FAC-PHC-BHOR',
    referringFacilityName: 'Bhor Primary Health Centre (PHC)',
    referringDoctorName: 'Dr. Ananya Deshmukh (MO)',
    destinationFacilityId: 'FAC-SGH-PUNE',
    destinationFacilityName: 'Sassoon General Hospital & B.J. Medical College, Pune',
    destinationDepartment: 'Obstetrics & High-Risk Pregnancy Unit',
    specialty: 'High-Risk Maternal Care',
    clinicalReason: 'Severe gestational pre-eclampsia (BP 162/106 mmHg), 34 weeks gestation, imminent risk of eclampsia',
    priority: 'CRITICAL',
    requiredDiagnostics: ['Complete Hemogram (Platelets)', 'Liver Function Tests', 'Serum Creatinine', 'Obstetric USG Doppler'],
    referralNotes: 'Patient administered loading dose of Magnesium Sulfate 4g IV. Transport arranged via 108 Emergency Ambulance. ASHA accompanying.',
    status: 'IN_TRANSIT',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    transitStartedAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'REF-MH-102',
    patientId: 'PAT004',
    patientName: 'Tukaram Shinde',
    patientAge: 62,
    patientGender: 'Male',
    patientPhone: '+91 94225 67890',
    abhaId: 'tukaram.shinde@abdm',
    referringFacilityId: 'FAC-PHC-BHOR',
    referringFacilityName: 'Bhor Primary Health Centre (PHC)',
    referringDoctorName: 'Dr. Ananya Deshmukh (MO)',
    destinationFacilityId: 'FAC-DH-AUNDH',
    destinationFacilityName: 'District Hospital Aundh, Pune',
    destinationDepartment: 'Chest Medicine / Pulmonology & NTEP',
    specialty: 'Pulmonology',
    clinicalReason: 'Subacute hemoptysis, chronic cough, right upper lobe opacity on screening X-Ray, suspected pulmonary Kochs / neoplasm',
    priority: 'URGENT',
    requiredDiagnostics: ['Sputum CBNAAT / GeneXpert', 'High Resolution CT Thorax', 'Bronchoscopy consultation'],
    referralNotes: 'Sputum sample collected for AFB. Patient hemodynamically stable. Transport voucher provided under Govt Scheme.',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    acceptedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'REF-MH-103',
    patientId: 'PAT007',
    patientName: 'Anand Vitthal Rao',
    patientAge: 48,
    patientGender: 'Male',
    patientPhone: '+91 99231 99887',
    abhaId: 'anand.rao@abdm',
    referringFacilityId: 'FAC-PHC-NASRAPUR',
    referringFacilityName: 'Nasrapur Primary Health Centre (PHC)',
    referringDoctorName: 'Dr. Vinod Borade',
    destinationFacilityId: 'FAC-SGH-PUNE',
    destinationFacilityName: 'Sassoon General Hospital, Pune',
    destinationDepartment: 'Ophthalmology Retina Clinic',
    specialty: 'Ophthalmology',
    clinicalReason: 'Proliferative diabetic retinopathy with early macular edema, blurred vision in right eye',
    priority: 'PRIORITY',
    requiredDiagnostics: ['Fundus Fluorescein Angiography (FFA)', 'OCT Macula'],
    referralNotes: 'Consultation completed at Sassoon Hospital. Counter-referral received. Advice: Strict glycemic control (HbA1c target < 7%), Nepafenac eye drops TID, return for laser in 4 weeks.',
    status: 'CONSULTATION_COMPLETED',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    acceptedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    outcomeSummary: 'PDR diagnosed. Focal argon laser photocoagulation performed. Patient discharged back to Bhor PHC for routine monitoring.',
    counterReferralAdvice: 'Monitor BP & fasting glucose weekly at PHC. Ensure adherence to anti-VEGF / laser protocol.',
  },
  {
    id: 'REF-MH-104',
    patientId: 'PAT005',
    patientName: 'Baby Aarav Khare',
    patientAge: 1.5,
    patientGender: 'Male',
    patientPhone: '+91 97664 12345',
    referringFacilityId: 'FAC-SC-VELU',
    referringFacilityName: 'Arogya Vardhini Sub-Centre Velu',
    referringDoctorName: 'ANM Rekha Gaikwad',
    destinationFacilityId: 'FAC-RH-BHOR',
    destinationFacilityName: 'Bhor Rural Hospital',
    destinationDepartment: 'Pediatrics / Nutritional Rehabilitation Centre (NRC)',
    specialty: 'Pediatrics',
    clinicalReason: 'Severe Acute Malnutrition (SAM) Grade 2 with visible muscle wasting, MUAC 11.2 cm, recurrent diarrhea',
    priority: 'PRIORITY',
    requiredDiagnostics: ['Hemoglobin', 'Blood Glucose', 'Serum Electrolytes', 'Stool Routine/Microscopy'],
    referralNotes: 'Enrolled in Maharashtra VCDC/NRC scheme. Mother counseled on therapeutic feeding and hygiene.',
    status: 'SCHEDULED',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
];

export const DEMO_DIAGNOSTICS: DiagnosticTestItem[] = [
  {
    id: 'DIAG-001',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    testCode: 'CBC-01',
    testName: 'Complete Blood Count (CBC / Hemogram)',
    category: 'PATHOLOGY',
    available: true,
    turnaroundHours: 2,
    slotsAvailableToday: 24,
    isFreeGovtSubsidized: true,
    instructions: 'No fasting required. Finger prick or venipuncture sample.',
  },
  {
    id: 'DIAG-002',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    testCode: 'RBS-01',
    testName: 'Random / Fasting Blood Glucose (Glucometer & Lab)',
    category: 'BIOCHEMISTRY',
    available: true,
    turnaroundHours: 1,
    slotsAvailableToday: 40,
    isFreeGovtSubsidized: true,
    instructions: 'Fasting 8-10 hours for FBS; 2 hours after meal for PPBS.',
  },
  {
    id: 'DIAG-003',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    testCode: 'TB-AFB',
    testName: 'Sputum Microscopy for AFB (NTEP Designated Center)',
    category: 'MICROBIOLOGY',
    available: true,
    turnaroundHours: 6,
    slotsAvailableToday: 15,
    isFreeGovtSubsidized: true,
    instructions: 'Early morning deep cough sputum in sterile container.',
  },
  {
    id: 'DIAG-004',
    facilityId: 'FAC-RH-BHOR',
    facilityName: 'Bhor Rural Hospital',
    testCode: 'XRAY-CHEST',
    testName: 'Digital Chest X-Ray (PA View)',
    category: 'IMAGING',
    available: true,
    turnaroundHours: 3,
    slotsAvailableToday: 18,
    isFreeGovtSubsidized: true,
    instructions: 'Remove metal objects and jewelry before imaging.',
  },
  {
    id: 'DIAG-005',
    facilityId: 'FAC-RH-BHOR',
    facilityName: 'Bhor Rural Hospital',
    testCode: 'USG-OBS',
    testName: 'Obstetric & Abdominal Ultrasonography (USG)',
    category: 'IMAGING',
    available: true,
    turnaroundHours: 4,
    slotsAvailableToday: 8,
    isFreeGovtSubsidized: true,
    instructions: 'Drink 1 litre of water 1 hour before pelvic ultrasound. Full bladder required.',
  },
  {
    id: 'DIAG-006',
    facilityId: 'FAC-RH-BHOR',
    facilityName: 'Bhor Rural Hospital',
    testCode: 'ECG-12',
    testName: '12-Lead Electrocardiogram (ECG)',
    category: 'BIOCHEMISTRY',
    available: true,
    turnaroundHours: 1,
    slotsAvailableToday: 35,
    isFreeGovtSubsidized: true,
    instructions: 'Lie flat and relax for 5 minutes during lead attachment.',
  },
  {
    id: 'DIAG-007',
    facilityId: 'FAC-DH-AUNDH',
    facilityName: 'District Hospital Aundh, Pune',
    testCode: 'HBA1C-HPLC',
    testName: 'HbA1c Glycated Hemoglobin (HPLC Gold Standard)',
    category: 'BIOCHEMISTRY',
    available: true,
    turnaroundHours: 12,
    slotsAvailableToday: 50,
    isFreeGovtSubsidized: true,
    instructions: 'No fasting required. Measures average glucose over 3 months.',
  },
  {
    id: 'DIAG-008',
    facilityId: 'FAC-DH-AUNDH',
    facilityName: 'District Hospital Aundh, Pune',
    testCode: 'LFT-KFT',
    testName: 'Comprehensive Liver & Kidney Panel (LFT / KFT)',
    category: 'BIOCHEMISTRY',
    available: true,
    turnaroundHours: 8,
    slotsAvailableToday: 40,
    isFreeGovtSubsidized: true,
    instructions: '10-12 hours overnight fasting recommended.',
  },
];

export const DEMO_MEDICINES: MedicineStockItem[] = [
  {
    id: 'MED-001',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Paracetamol',
    genericName: 'Paracetamol IP',
    dosageForm: 'TABLET',
    strength: '500 mg',
    quantityAvailable: 4200,
    status: 'AVAILABLE',
    lastUpdated: 'Today, 8:00 AM',
  },
  {
    id: 'MED-002',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Amoxicillin + Potassium Clavulanate',
    genericName: 'Amox-Clav IP',
    dosageForm: 'TABLET',
    strength: '625 mg',
    quantityAvailable: 680,
    status: 'AVAILABLE',
    lastUpdated: 'Today, 8:00 AM',
  },
  {
    id: 'MED-003',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Metformin Hydrochloride',
    genericName: 'Metformin IP',
    dosageForm: 'TABLET',
    strength: '500 mg',
    quantityAvailable: 1540,
    status: 'AVAILABLE',
    lastUpdated: 'Today, 8:00 AM',
  },
  {
    id: 'MED-004',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Amlodipine Besylate',
    genericName: 'Amlodipine IP',
    dosageForm: 'TABLET',
    strength: '5 mg',
    quantityAvailable: 890,
    status: 'AVAILABLE',
    lastUpdated: 'Today, 8:00 AM',
  },
  {
    id: 'MED-005',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Telmisartan',
    genericName: 'Telmisartan IP',
    dosageForm: 'TABLET',
    strength: '40 mg',
    quantityAvailable: 45,
    status: 'LIMITED',
    lastUpdated: 'Today, 8:00 AM',
    alternativeFacility: {
      facilityName: 'Bhor Rural Hospital',
      distanceKm: 3.2,
      phone: '+91 02113 222340',
    },
  },
  {
    id: 'MED-006',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Iron and Folic Acid (IFA) Red',
    genericName: 'Ferrous Sulfate 100mg + Folic Acid 0.5mg',
    dosageForm: 'TABLET',
    strength: 'Standard Adult IFA',
    quantityAvailable: 5200,
    status: 'AVAILABLE',
    lastUpdated: 'Today, 8:00 AM',
  },
  {
    id: 'MED-007',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Oral Rehydration Salts (ORS)',
    genericName: 'WHO Recommended ORS Formulation',
    dosageForm: 'POWDER',
    strength: '20.5 g sachet',
    quantityAvailable: 1200,
    status: 'AVAILABLE',
    lastUpdated: 'Today, 8:00 AM',
  },
  {
    id: 'MED-008',
    facilityId: 'FAC-PHC-BHOR',
    facilityName: 'Bhor Primary Health Centre (PHC)',
    medicineName: 'Rabies Vaccine (Cell Culture)',
    genericName: 'Anti-Rabies Vaccine (ARV) IP',
    dosageForm: 'INJECTION',
    strength: 'Single Dose Vial 0.5ml',
    quantityAvailable: 0,
    status: 'OUT_OF_STOCK',
    lastUpdated: 'Today, 8:00 AM',
    alternativeFacility: {
      facilityName: 'Bhor Rural Hospital (Cold Chain Room)',
      distanceKm: 3.2,
      phone: '+91 02113 222340',
    },
  },
  {
    id: 'MED-009',
    facilityId: 'FAC-RH-BHOR',
    facilityName: 'Bhor Rural Hospital',
    medicineName: 'Polyvalent Anti-Snake Venom (ASV)',
    genericName: 'Equine Polyvalent Snake Antivenom IP',
    dosageForm: 'INJECTION',
    strength: '10 ml Vial Lyophilized',
    quantityAvailable: 32,
    status: 'AVAILABLE',
    lastUpdated: 'Today, 8:00 AM',
  },
  {
    id: 'MED-010',
    facilityId: 'FAC-RH-BHOR',
    facilityName: 'Bhor Rural Hospital',
    medicineName: 'Human Regular Insulin (rDNA)',
    genericName: 'Soluble Insulin Injection IP',
    dosageForm: 'INJECTION',
    strength: '40 IU/ml Vial',
    quantityAvailable: 18,
    status: 'LIMITED',
    lastUpdated: 'Today, 8:00 AM',
    alternativeFacility: {
      facilityName: 'District Hospital Aundh, Pune',
      distanceKm: 42,
      phone: '+91 020 2728 0100',
    },
  },
];

export const DEMO_HIGH_RISK_FOLLOWUPS: HighRiskFollowup[] = [
  {
    id: 'FOL-001',
    patientId: 'PAT002',
    patientName: 'Sunita Tai More',
    patientPhone: '+91 98220 54321',
    age: 26,
    village: 'Velu Gaon, Bhor',
    category: 'MATERNAL',
    subCategory: 'High-Risk Pregnancy (34 Wks, Pre-eclampsia / BP 162/106)',
    assignedAshaId: 'ASHA-001',
    assignedAshaName: 'Asha Tai Vandana More',
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    lastVisitDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: 'ESCALATED',
    riskFactors: ['High Blood Pressure > 160/100', 'Persistent Frontal Headache', 'Bilateral Pedal Edema'],
    nextAction: 'Ensure safe ambulance transit to Sassoon Hospital. Accompany patient and track admission.',
    notes: 'Husband alerted. Janani Shishu Suraksha Karyakram (JSSK) benefits activated.',
  },
  {
    id: 'FOL-002',
    patientId: 'PAT005',
    patientName: 'Baby Aarav Khare',
    patientPhone: '+91 97664 12345',
    age: 1.5,
    village: 'Kapurhol, Bhor',
    category: 'CHILD',
    subCategory: 'Severe Acute Malnutrition (SAM) & Missed Pentavalent-3',
    assignedAshaId: 'ASHA-001',
    assignedAshaName: 'Asha Tai Vandana More',
    dueDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    lastVisitDate: new Date(Date.now() - 10 * 86400000).toISOString(),
    status: 'OVERDUE',
    riskFactors: ['MUAC < 11.5 cm', 'Weight-for-height below -3 SD', 'Immunization gap > 4 weeks'],
    nextAction: 'Home visit urgently required. Provide therapeutic energy paste and escort to Bhor RH NRC.',
    notes: 'Mother contacted by phone; scheduled visit for tomorrow morning.',
  },
  {
    id: 'FOL-003',
    patientId: 'DEMO-003',
    patientName: 'Ramesh Patil',
    patientPhone: '+91 97222 33445',
    age: 54,
    village: 'Velu Gaon, Bhor',
    category: 'CHRONIC_NCD',
    subCategory: 'Type-2 Diabetes & Hypertension (Stage 2 HTN)',
    assignedAshaId: 'ASHA-001',
    assignedAshaName: 'Asha Tai Vandana More',
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    lastVisitDate: new Date(Date.now() - 25 * 86400000).toISOString(),
    status: 'DUE',
    riskFactors: ['Fasting Glucose > 180 mg/dL', 'Medication stock nearly empty', 'Skipped last eye checkup'],
    nextAction: 'Deliver monthly Amlodipine & Metformin refill from PHC. Check glucometer reading.',
    notes: 'Patient reports mild numbness in right foot toes (early diabetic neuropathy).',
  },
  {
    id: 'FOL-004',
    patientId: 'PAT007',
    patientName: 'Anand Vitthal Rao',
    patientPhone: '+91 99231 99887',
    age: 48,
    village: 'Nasrapur',
    category: 'POST_REFERRAL',
    subCategory: 'Counter-Referral Care: Post-Retinal Laser Surgery',
    assignedAshaId: 'ASHA-002',
    assignedAshaName: 'Asha Tai Sunita Kamble',
    dueDate: new Date(Date.now() + 6 * 86400000).toISOString(),
    lastVisitDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'DUE',
    riskFactors: ['Recent invasive retinal photocoagulation', 'Risk of vitreous hemorrhage with heavy lifting'],
    nextAction: 'Ensure eye drops instillations twice daily and confirm follow-up slot at Sassoon Hospital.',
    notes: 'Vision improving gradually according to patient feedback.',
  },
];

export const DEMO_PROGRESS_REPORTS: Record<string, DoctorProgressReportData> = {
  'DEMO-003': {
    patientId: 'DEMO-003',
    patientName: 'Ramesh Patil',
    age: 54,
    gender: 'Male',
    chronicConditions: ['Type-2 Diabetes Mellitus', 'Essential Hypertension', 'Mild Dyslipidemia'],
    vitalsTrend: [
      { date: '3 Months Ago', bpSystolic: 158, bpDiastolic: 98, fastingSugar: 195, weightKg: 78.5, pulse: 82 },
      { date: '2 Months Ago', bpSystolic: 152, bpDiastolic: 94, fastingSugar: 178, weightKg: 77.8, pulse: 80 },
      { date: '1 Month Ago', bpSystolic: 146, bpDiastolic: 92, fastingSugar: 160, weightKg: 76.9, pulse: 78 },
      { date: 'Today (PHC Visit)', bpSystolic: 142, bpDiastolic: 90, fastingSugar: 148, weightKg: 76.2, pulse: 76 },
    ],
    medicationAdherencePercent: 88,
    diagnosticHistory: [
      { date: '3 Months Ago', testName: 'HbA1c (Glycated Hb)', value: '8.8 %', referenceRange: '< 7.0 %', status: 'ABNORMAL' },
      { date: '1 Month Ago', testName: 'Fasting Blood Sugar', value: '160 mg/dL', referenceRange: '70-100 mg/dL', status: 'ABNORMAL' },
      { date: '1 Month Ago', testName: 'Serum Creatinine', value: '1.05 mg/dL', referenceRange: '0.7-1.3 mg/dL', status: 'NORMAL' },
      { date: 'Today', testName: 'Random Blood Sugar (Glucometer)', value: '148 mg/dL', referenceRange: '< 140 mg/dL', status: 'NORMAL' },
    ],
    consultationMilestones: [
      { date: '3 Months Ago', facility: 'Bhor PHC', doctorName: 'Dr. Ananya Deshmukh', summary: 'Diagnosed uncontrolled Stage 2 HTN. Initiated Telmisartan 40mg + Metformin 500mg BD.' },
      { date: '1 Month Ago', facility: 'Bhor Rural Hospital', doctorName: 'Dr. Rahul Verma', summary: 'Added Amlodipine 5mg. Diet and salt reduction counseling given.' },
      { date: 'Today', facility: 'Bhor PHC', doctorName: 'Dr. Ananya Deshmukh', summary: 'Steady clinical improvement. BP dropping towards target 130/80. Continue regimen.' },
    ],
    referralProgress: {
      hasReferral: false,
    },
    clinicalEvolutionNotes: 'Patient is demonstrating favorable response to combination antihypertensive therapy. Systolic BP has decreased by 16 mmHg over 90 days. Fasting blood glucose has improved from 195 to 148 mg/dL with dietary modification and regular morning walks in Velu village. Reinforce smoking abstinence and eye clinic attendance.',
  },
  'PAT002': {
    patientId: 'PAT002',
    patientName: 'Sunita Tai More',
    age: 26,
    gender: 'Female',
    chronicConditions: ['Primigravida 34 Weeks', 'Gestational Hypertension / Pre-Eclampsia'],
    vitalsTrend: [
      { date: '4 Weeks Ago', bpSystolic: 122, bpDiastolic: 80, weightKg: 58.0, pulse: 78 },
      { date: '2 Weeks Ago', bpSystolic: 136, bpDiastolic: 88, weightKg: 60.5, pulse: 84 },
      { date: '1 Week Ago', bpSystolic: 148, bpDiastolic: 96, weightKg: 62.0, pulse: 90 },
      { date: 'Today (Triage)', bpSystolic: 162, bpDiastolic: 106, weightKg: 63.4, pulse: 96 },
    ],
    medicationAdherencePercent: 95,
    diagnosticHistory: [
      { date: 'Today', testName: 'Urine Albumin (Dipstick)', value: '3+ (Severe)', referenceRange: 'Negative', status: 'CRITICAL' },
      { date: 'Today', testName: 'Platelet Count', value: '110,000 /uL', referenceRange: '150,000-450,000', status: 'ABNORMAL' },
      { date: 'Today', testName: 'Serum Uric Acid', value: '7.2 mg/dL', referenceRange: '2.4-6.0 mg/dL', status: 'ABNORMAL' },
    ],
    consultationMilestones: [
      { date: '2 Weeks Ago', facility: 'Velu Sub-Centre', doctorName: 'ANM Rekha Gaikwad', summary: 'Mild BP rise noted. Advised rest and PHC medical review.' },
      { date: 'Today', facility: 'Bhor PHC', doctorName: 'Dr. Ananya Deshmukh', summary: 'Emergency pre-eclampsia diagnosis. Loading MgSO4 administered. Transferred via 108 to Sassoon General Hospital.' },
    ],
    referralProgress: {
      hasReferral: true,
      referralId: 'REF-MH-101',
      destination: 'Sassoon General Hospital, Pune',
      status: 'IN_TRANSIT',
      summary: 'Emergency 108 transfer active. ETA at Sassoon Hospital: 42 minutes.',
    },
    clinicalEvolutionNotes: 'Accelerated rise in blood pressure over the past 14 days culminating in severe pre-eclampsia at 34 weeks gestation. Pedal edema has progressed to anasarca. Prompt tertiary escalation is lifesaving to prevent maternal convulsions (eclampsia) and fetal compromise.',
  },
};
